// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kzJxTN2BTHu7U2QQqklUr5HCqmNF3Hk',
    appId: '1:594430632741:web:dd4e2568fa8857822eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    authDomain: 'ecommerce-9d588.firebaseapp.com',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    measurementId: 'G-1JHSNP2GRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2aAlES3d6Hxf1XPiEGN4jE2fGtk_tGY',
    appId: '1:594430632741:android:e6b7f0a255eb888f2eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Ko3eXNMHnzTodVXr5lIR1XQwsQh9o7k',
    appId: '1:594430632741:ios:30293cda90faf3b52eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Ko3eXNMHnzTodVXr5lIR1XQwsQh9o7k',
    appId: '1:594430632741:ios:30293cda90faf3b52eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-kzJxTN2BTHu7U2QQqklUr5HCqmNF3Hk',
    appId: '1:594430632741:web:d3af72de7bd36ed52eb0cc',
    messagingSenderId: '594430632741',
    projectId: 'ecommerce-9d588',
    authDomain: 'ecommerce-9d588.firebaseapp.com',
    storageBucket: 'ecommerce-9d588.firebasestorage.app',
    measurementId: 'G-N4ZQF5DMKR',
  );
}
